# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlamofireExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  # Pods for AlamofireExample

  target 'AlamofireExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlamofireExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
