# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPodsExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'Then'
  # Pods for CocoaPodsExample

end
