# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Omok' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  # Pods for Omok

end
