# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestRXAmalofire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxAlamofire'
  pod 'RxCocoa', '~> 5'
  # Pods for TestRXAmalofire

end
